AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template to deploy a static website (SWSE Starship Architect) on S3 with CloudFront and ACM Certificate, using Origin Access Control (OAC).'

Parameters:
  DomainName:
    Type: String
    Default: swse.starship.dimble.net
    Description: The domain name for the website.

  HostedZoneId:
    Type: String
    Description: The Route 53 Hosted Zone ID for the domain (e.g. dimble.net).

Resources:
  # S3 Bucket for Website Hosting
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'swse-starship-${AWS::AccountId}-${AWS::Region}'
      # Enable full block of public access
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  # CloudFront Origin Access Control
  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub 'swse-oac-${AWS::StackName}'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  # Bucket Policy to Allow Access only from CloudFront OAC
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: 's3:GetObject'
            Resource: !Sub 'arn:aws:s3:::${WebsiteBucket}/*'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}'

  # ACM Certificate with DNS Validation
  Certificate:
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      ValidationMethod: DNS
      DomainValidationOptions:
        - DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId

  # CloudFront Distribution
  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        Origins:
          - Id: S3Origin
            # Use the Regional Domain Name for OAC
            DomainName: !GetAtt WebsiteBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: '' # Must be empty when using OAC
            OriginAccessControlId: !Ref CloudFrontOAC
        Enabled: true
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
            - OPTIONS
          Compress: true
          # Managed-CachingOptimized Policy (658327ea-f89d-4fab-a63d-7e88639e58f6)
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          # Managed-CORS-S3Origin Policy (88a5eaf4-2fd4-4709-b370-b4c650ea3fcf)
          OriginRequestPolicyId: 88a5eaf4-2fd4-4709-b370-b4c650ea3fcf
          # Managed-SecurityHeadersPolicy (67f7725c-df29-4744-9ea2-019197abb8bf)
          ResponseHeadersPolicyId: 67f7725c-df29-4744-9ea2-019197abb8bf
        ViewerCertificate:
          AcmCertificateArn: !Ref Certificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        # Custom Error Response to handle SPA routing (optional but recommended for Vue apps)
        CustomErrorResponses:
          - ErrorCode: 403 # Access Denied (S3 returns 403 for missing objects in private buckets)
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html

  # Route 53 Record Set for CloudFront Alias
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A
      AliasTarget:
        HostedZoneId: Z2FDTNDATAQYW2 # CloudFront Fixed Zone ID
        DNSName: !GetAtt CloudFrontDistribution.DomainName

Outputs:
  BucketName:
    Value: !Ref WebsiteBucket
    Description: Name of the S3 Bucket

  DistributionId:
    Value: !Ref CloudFrontDistribution
    Description: CloudFront Distribution ID

  CloudFrontDomainName:
    Value: !GetAtt CloudFrontDistribution.DomainName
    Description: CloudFront Domain Name
